### ISSUE TITLE
Random's unit test is failing on macOS

### ISSUE THREAD

**Issue by catap** [jgrapht/jgrapht#1107]
```
 * JGraphT version: e36523ab8a356c797bde56c992735efe3f1221ac
 * Java version (java -version)/platform:  OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)
```

**Issue**

Random based tests are failing.

Stacktraces:
1)
```
java.lang.ArrayIndexOutOfBoundsException: Index 5859 out of bounds for length 58

	at org.jgrapht.core/org.jgrapht.util.RadixSort.radixSort(RadixSort.java:72)
	at org.jgrapht.core/org.jgrapht.util.RadixSort.sort(RadixSort.java:103)
	at org.jgrapht.core/org.jgrapht.util.RadixSortTest.testRandomArrays(RadixSortTest.java:124)
	at org.jgrapht.core/org.jgrapht.util.RadixSortTest.testRandomArraysWithNoFixedSeed(RadixSortTest.java:108)
```

2)
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 41

	at org.jgrapht.core/org.jgrapht.util.RadixSort.radixSort(RadixSort.java:72)
	at org.jgrapht.core/org.jgrapht.util.RadixSort.sort(RadixSort.java:103)
	at org.jgrapht.core/org.jgrapht.alg.isomorphism.AHURootedTreeIsomorphismInspector.isomorphismExists(AHURootedTreeIsomorphismInspector.java:244)
	at org.jgrapht.core/org.jgrapht.alg.isomorphism.AHURootedTreeIsomorphismInspector.isomorphismExists(AHURootedTreeIsomorphismInspector.java:290)
	at org.jgrapht.core/org.jgrapht.alg.isomorphism.AHUUnrootedTreeIsomorphismInspector.isomorphismExists(AHUUnrootedTreeIsomorphismInspector.java:151)
	at org.jgrapht.core/org.jgrapht.alg.isomorphism.AHUUnrootedTreeIsomorphismInspectorTest.testRandomTrees(AHUUnrootedTreeIsomorphismInspectorTest.java:461)
```

**Steps to reproduce (small coding example)**

just run unit test on this platform

**Expected behaviour**

Tests should pass

**Other information**

**Comment by jsichi** [comment]
Maybe we should see if we can get macOS into our continuous integration?

**Comment by jsichi** [comment]
The first stacktrace is from a random seed, meaning we would need to determine the seed in order to repro.

However, the second stacktrace is from a fixed seed.  Since the same test passes on Linux, this indicates that it is indeed macOS which is required for the failure (not some platform-independent bug which only gets tripped by a random seed).  We'll probably need to investigate the bit fiddling in RadixSort.

If someone with access to a macOS dev environment can reproduce the AHUUnrootedTreeIsomorphismInspectorTest failure and capture the input to RadixSort which causes the exception, that would be a good place to start.

**Comment by catap** [comment]
@jsichi I've run it via Intellij IDEA, let me try to re-run it from CLI. Maybe it affects.

**Comment by besza** [comment]
@jsichi We can do a matrix-build for the pre-merge (PR) checks targeting {macos-latest, ubuntu-latest} x {11-temurin, 11-zulu}. (We can adapt the master branch workflow as well, but we would have to modularize it a bit, such that we do not run specifics steps multiple times.)

**Comment by jsichi** [comment]
@besza let's wait until this issue gets resolved and then macOS build/test runs clean; otherwise, we may end up causing spurious failures on unrelated PR's.  After that, we can start with enabling the pre-merge checks, and then move on to the master branch.
