### ISSUE TITLE
Ant unzip task fails because of class name containing non-ascii chars (SørensenIndexLinkPrediction.java)

### ISSUE THREAD

**Issue by lemmy** [jgrapht/jgrapht#1112]
```
[2022-02-08T03:57:50.649Z]     [unzip] Expanding: /workspaces/CommunityModules/lib/jgrapht-core-1.5.1.jar into /workspaces/CommunityModules/build/deps
[2022-02-08T03:57:50.846Z] 
2022-02-08T03:57:52: BUILD FAILED
2022-02-08T03:57:52: /workspaces/CommunityModules/build.xml:55: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /workspaces/CommunityModules/build/deps/org/jgrapht/alg/linkprediction/S?rensenIndexLinkPrediction.class
2022-02-08T03:57:52: 	at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:121)
2022-02-08T03:57:52: 	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:68)
2022-02-08T03:57:52: 	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
2022-02-08T03:57:52: 	at java.base/java.io.File.toPath(File.java:2387)
2022-02-08T03:57:52: 	at org.apache.tools.ant.taskdefs.Expand.extractFile(Expand.java:361)
2022-02-08T03:57:52: 	at org.apache.tools.ant.taskdefs.Expand.expandFile(Expand.java:199)
2022-02-08T03:57:52: 	at org.apache.tools.ant.taskdefs.Expand.execute(Expand.java:157)
2022-02-08T03:57:52: 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
2022-02-08T03:57:52: 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
2022-02-08T03:57:52: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-02-08T03:57:52: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-02-08T03:57:52: 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
2022-02-08T03:57:52: 	at org.apache.tools.ant.Task.perform(Task.java:350)
2022-02-08T03:57:52: 	at org.apache.tools.ant.Target.execute(Target.java:449)
2022-02-08T03:57:52: 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
2022-02-08T03:57:52: 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
2022-02-08T03:57:52: 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
2022-02-08T03:57:52: 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
2022-02-08T03:57:52: 	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
2022-02-08T03:57:52: 	at org.apache.tools.ant.Main.runBuild(Main.java:830)
2022-02-08T03:57:52: 	
[2022-02-08T03:57:50.847Z] at org.apache.tools.ant.Main.startAnt(Main.java:223)
[2022-02-08T03:57:50.848Z] 
2022-02-08T03:57:52: 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
2022-02-08T03:57:52: 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
[2022-02-08T03:57:50.848Z] 
```

https://github.com/tlaplus/CommunityModules/commit/e341a43d4c5e3392420e17280e3a9ea7ca9af82d

**Comment by jsichi** [comment]
I'm going to close this since it seems like a problem with ant, not JGraphT.  Long ago we used to stick to ASCII only for filenames and source code, but it's 2022 now.
