### ISSUE TITLE
"invalid handle" when using AStar

### ISSUE THREAD

**Issue by linxinyaooo** [jgrapht/jgrapht#1123]
```
 * JGraphT version: 15.0
 * Java version (java -version)/platform:  macOS
```

**Issue**
when running AStarShortestPath or BidirectionalAStarShortestPath.
decreasedKey(pairing Heap) errors

> Exception in thread "main" java.lang.IllegalArgumentException: Invalid handle!
	at org.jheaps@0.14/org.jheaps.tree.PairingHeap.decreaseKey(PairingHeap.java:426)
	at org.jheaps@0.14/org.jheaps.tree.PairingHeap.access$000(PairingHeap.java:90)
	at org.jheaps@0.14/org.jheaps.tree.PairingHeap$Node.decreaseKey(PairingHeap.java:364)
	at org.jgrapht.core/org.jgrapht.alg.shortestpath.BidirectionalAStarShortestPath$AStarSearchFrontier.updateDistance(BidirectionalAStarShortestPath.java:273)
	at org.jgrapht.core/org.jgrapht.alg.shortestpath.BidirectionalAStarShortestPath.getPath(BidirectionalAStarShortestPath.java:178)
	at org.jgrapht.io/org.jgrapht.nio.ShortestPathDemo.main(ShortestPathDemo.java:96)

**Steps to reproduce (small coding example)**

**Expected behaviour**

**Other information**

**Comment by linxinyaooo** [comment]
when I debug  I found
`private void decreaseKey(Node<K, V> n, K newKey) {
        int c;
        if (this.comparator == null) {
            c = ((Comparable)newKey).compareTo(n.key);
        } else {
            c = this.comparator.compare(newKey, n.key);
        }

        if (c > 0) {
            throw new IllegalArgumentException("Keys can only be decreased!");
        } else {
            n.key = newKey;
            if (c != 0 && this.root != n) {
                if (n.o_s == null) {
                    throw new IllegalArgumentException("Invalid handle!");`

but n.o_s(this.o_s) is not null

**Comment by AlanLahoud** [comment]
I have faced this issue when my heuristics were not admissible (not always though). I would check if you get rid of your error by setting a (small) upperbound in the euclidean distance matrix.
