### ISSUE TITLE
GraphMLImporter unable to open graphml.xsd

### ISSUE THREAD

**Issue by pmanningjr** [jgrapht/jgrapht#310]
Dear authors, 

First of all congratulations on an amazing new release! I've been excited to dive in. 

I'm attempting to import a GraphML file using the new GraphMLImporter and it seems to be failing when it tries to read in the graphml.xsd resource. The program isn't throwing the "Failed to locate GraphML xsd" ImportException message, so it appears that it is able to locate the resource, however it is throwing the overall Exception message, "Failed to parse GraphML". Below is the entire stack trace. I'm using Maven for dependency management within NetBeans 8.1. Any help resolving this issue would be greatly appreciated. Thanks ahead of time (and apologies if this is my own stupid issue).  

Peter

org.jgrapht.ext.ImportException: Failed to parse GraphML
	at org.jgrapht.ext.GraphMLImporter.importGraph(GraphMLImporter.java:252)
	at org.jgrapht.ext.GraphImporter.importGraph(GraphImporter.java:68)
	at com.ssl.graphmltest.DCPGraphReader.getGraph(DCPGraphReader.java:37)
	at com.ssl.graphmltest.GraphMLTest.main(GraphMLTest.java:22)
Caused by: org.jgrapht.ext.ImportException: Failed to parse GraphML
	at org.jgrapht.ext.GraphMLImporter.createXMLReader(GraphMLImporter.java:280)
	at org.jgrapht.ext.GraphMLImporter.importGraph(GraphMLImporter.java:243)
	... 3 more
Caused by: org.xml.sax.SAXParseException; schema_reference.4: Failed to read schema document 'file:/C:/Users/manningp/dcpdev/GraphMLTest/file:/C:/Users/manningp/.m2/repository/org/jgrapht/jgrapht-ext/1.0.0/jgrapht-ext-1.0.0.jar!/graphml.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:306)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4162)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4145)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument1(XSDHandler.java:2475)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2183)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:569)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:613)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:572)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadGrammar(XMLSchemaLoader.java:538)
	at com.sun.org.apache.xerces.internal.jaxp.validation.XMLSchemaFactory.newSchema(XMLSchemaFactory.java:255)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:638)
	at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:654)
	at org.jgrapht.ext.GraphMLImporter.createXMLReader(GraphMLImporter.java:269)
	... 4 more
Caused by: java.io.FileNotFoundException: C:\Users\manningp\dcpdev\GraphMLTest\file:\C:\Users\manningp\.m2\repository\org\jgrapht\jgrapht-ext\1.0.0\jgrapht-ext-1.0.0.jar!\graphml.xsd (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:582)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:685)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaDOMParser.parse(SchemaDOMParser.java:530)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2171)
	... 12 more
Error: Failed to parse GraphML

**Comment by d-michail** [comment]
Could you check if the [GraphMLDemo](https://github.com/jgrapht/jgrapht/blob/master/jgrapht-demo/src/main/java/org/jgrapht/demo/GraphMLDemo.java) (was not there at the time of the 1.0.0 release) works properly on your system?

**Comment by pmanningjr** [comment]
Hi, 

Thank you for responding - looking forward to getting this resolved. 

I'm assuming I should update with all the changes since 1.0.0 since GraphMLDemo references ComponentNameProvider and ComponentAttributeProvider (not present in 1.0.0)?

**Comment by pmanningjr** [comment]
Hi, 

I'm able to run GraphMLDemo (Master) using Eclipse, so it appears that there must be some classpath dependency issue within NetBeans / Maven that isn't being set properly out of the box. If you notice in the error, there is the file path: 

"C:\Users\manningp\dcpdev\GraphMLTest\file:\C:\Users\manningp.m2\repository\org\jgrapht\jgrapht-ext\1.0.0\jgrapht-ext-1.0.0.jar!\graphml.xsd (The filename, directory name, or volume label syntax is incorrect)"

that seems to have concatenated the working directory of my project (GraphMLTest) with the path of the graphml.xsd resource. Do you or any of your team have any guesses on how to resolve this kind of issue within NetBeans/Maven? Thanks again. 

Peter

**Comment by d-michail** [comment]
You can change `ComponentNameProvider` to `VertexNameProvider` and `IntegerComponentNameProvider` to `IntegerEdgeNameProvider`.

**Comment by d-michail** [comment]
I do not think you are doing something wrong. This is probably a bug of the importer. I will have a closer look ASAP.

**Comment by d-michail** [comment]
Could you test this [branch](https://github.com/d-michail/jgrapht/tree/graphml-importer-xsd-bugfix)?

Just clone it and install using 
```
git clone git@github.com:d-michail/jgrapht.git --branch graphml-importer-xsd-bugfix
cd jgrapht
mvn install
```
and change your pom.xml to use 1.0.1-SNAPSHOT as the version of the jgrapht-ext and jgrapht-core
```
<dependency>
    <groupId>org.jgrapht</groupId>
    <artifactId>jgrapht-ext</artifactId>
    <version>1.0.1-SNAPSHOT</version>
</dependency>
```
Thanks!

**Comment by pmanningjr** [comment]
Hi, 

The fix completely worked! Do you mind me asking what the issue was for curiosity / educational sake? Thanks for taking care of that. I'm guessing this will be part of the 1.0.1 release?

**Comment by d-michail** [comment]
Perfect! 

As you mentioned previously, the path was not formed properly. We were locating the filename and the resolution was happening inside the validator which for some reason failed. Now the resolution of the filename happens before and we provide an input stream to the validator. 

However, this only manifested when using the dependency from maven .m2/ folder and not inside the unit tests which use the dependencies directly from the target/ folder.

**Comment by d-michail** [comment]
Thanks for reporting this!
