### ISSUE TITLE
Strange problem with isomorphism

### ISSUE THREAD

**Issue by tidus8** [jgrapht/jgrapht#34]
Hi,

I have a strange problem in my code....

I'm working with isomorphisms my code give me an error when I try to do an isomorphism over two particular graphs....

I'm using this:

AdaptiveIsomorphismInspectorFactory.createIsomorphismInspector(graph,graph2).isIsomorphic()

and I have this error:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
    at org.jgrapht.experimental.isomorphism.EquivalenceIsomorphismInspector.createPermutationIterator(Unknown Source)
    at org.jgrapht.experimental.isomorphism.AbstractExhaustiveIsomorphismInspector.init(Unknown Source)
    at org.jgrapht.experimental.isomorphism.AbstractExhaustiveIsomorphismInspector.<init>(Unknown Source)
    at org.jgrapht.experimental.isomorphism.EquivalenceIsomorphismInspector.<init>(Unknown Source)
    at org.jgrapht.experimental.isomorphism.AdaptiveIsomorphismInspectorFactory.createTopologicalExhaustiveInspector(Unknown Source)
    at org.jgrapht.experimental.isomorphism.AdaptiveIsomorphismInspectorFactory.createAppropriateConcreteInspector(Unknown Source)
    at org.jgrapht.experimental.isomorphism.AdaptiveIsomorphismInspectorFactory.createIsomorphismInspector(Unknown Source)
    at org.jgrapht.experimental.isomorphism.AdaptiveIsomorphismInspectorFactory.createIsomorphismInspector(Unknown Source)

over thousands of graphs it works, but over those two graphs it doesn't work....
why?

Any advice??

Thanks

**Comment by gabbage** [comment]
I'm having the same error. as an example, these two graphs can reproduce the error:
([0, 1, 2, 3], [(0 : 2)=(0,2), (1 : 3)=(1,3), (2 : 1)=(2,1), (2 : 3)=(2,3), (3 : 0)=(3,0), (3 : 2)=(3,2)])
([1, 2, 3, 4], [(1 : 3)=(1,3), (1 : 4)=(1,4), (3 : 2)=(3,2), (4 : 2)=(4,2)])

**Comment by jsichi** [comment]
The old experimental isomorphism implementation is being deleted and replaced with the new VF2 package:

http://jgrapht-users.107614.n3.nabble.com/ismorphism-td4025020.html

If you pull the latest code, you can test that out and see if it solves your problem.
