### ISSUE TITLE
IndexOutOfBoundsException in FibonacciHeap

### ISSUE THREAD

**Issue by shevek** [jgrapht/jgrapht#518]
```
Caused by: java.lang.IndexOutOfBoundsException: Index: 3, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.jgrapht.util.FibonacciHeap.consolidate(FibonacciHeap.java:461)
	at org.jgrapht.util.FibonacciHeap.removeMin(FibonacciHeap.java:263)
	at org.jgrapht.traverse.ClosestFirstIterator.provideNextVertex(ClosestFirstIterator.java:252)
	at org.jgrapht.traverse.CrossComponentIterator.next(CrossComponentIterator.java:194)
	at CustomerCode.toGraphViz(CustomerCode.java:339)
	at org.anarres.graphviz.builder.GraphVizUtils.toGraphVizGraph(GraphVizUtils.java:57)
	at org.anarres.graphviz.builder.GraphVizUtils.toGraphVizFile(GraphVizUtils.java:69)
```

I don't even know where to start on this, and today isn't a good day for me to debug it. As far as I can tell, CustomerCode contains a correct usage of ClosestFirstIterator. The line is:
```
ClosestFirstIterator<> it = new ClosestFirstIterator<>(graph, initset, 3);
while (it.hasNext()) {
    N node = it.next(); // This threw.
    // ...
}
```

The graph isn't abnormally large or anything.

jgrapht 1.1.0 from Maven Central.

**Comment by shevek** [comment]
Looking at it, there's an inner loop with an integer variable `d` and I couldn't prove in a very short space of time that the increment of `d` was in any way bounded by the size of the list. In fact, I just wrote a fuzz-test for CrossComponentIterator, and I'm hitting other NPEs, too.

**Comment by shevek** [comment]
Related:
```
    java.lang.NullPointerException
        at org.jgrapht.util.FibonacciHeap.decreaseKey(FibonacciHeap.java:129)
        at org.jgrapht.traverse.ClosestFirstIterator.encounterVertexAgain(ClosestFirstIterator.java:242)
        at CustomerCode$1CFI.encounterVertexAgain(CustomerCode.java:356) // for logging
        at org.jgrapht.traverse.CrossComponentIterator.addUnseenChildrenOf(CrossComponentIterator.java:307)
        at org.jgrapht.traverse.CrossComponentIterator.next(CrossComponentIterator.java:199)
        at org.compilerworks.plugin.lineage.report.LineagePipelineGraphviz.toGraphViz(LineagePipelineGraphviz.java:365)
        at org.anarres.graphviz.builder.GraphVizUtils.toGraphVizGraph(GraphVizUtils.java:57)
        at org.anarres.graphviz.builder.GraphVizUtils.toGraphVizFile(GraphVizUtils.java:69)
```

**Comment by shevek** [comment]
Using Iterators.limit(new BreadthFirstIterator(...), 30) works just fine.
Removing the custom specifics, and using a simple DefaultDirectedGraph and ClosestFirstIterator also seems to work fine, so there's something going on in custom specifics? Although I can't right now see what, as it's just using an ObjectSet instead of a HashMap.

**Comment by shevek** [comment]
Result of running a few hundred customer examples through CFI with standard DDG:
```
CustomTest > test FAILED
    java.lang.NullPointerException
        at org.jgrapht.util.FibonacciHeap.decreaseKey(FibonacciHeap.java:129)
        at org.jgrapht.traverse.ClosestFirstIterator.encounterVertexAgain(ClosestFirstIterator.java:242)
        at org.jgrapht.traverse.CrossComponentIterator.addUnseenChildrenOf(CrossComponentIterator.java:307)
        at org.jgrapht.traverse.CrossComponentIterator.next(CrossComponentIterator.java:199)
        at CustomerCode.toGraphViz(CustomerCode.java:374)
        at org.anarres.graphviz.builder.GraphVizUtils.toGraphVizGraph(GraphVizUtils.java:57)
        at org.anarres.graphviz.builder.GraphVizUtils.toGraphVizFile(GraphVizUtils.java:69)
        at org.compilerworks.plugin.lang.fb.dataswarm.CustomTest.test(CustomTest.java:42)
```

**Comment by jsichi** [comment]
I'm biting my nails here...

**Comment by jsichi** [comment]
If it's possible to extract the raw structure of the customer graph, eliminating any customer data labels, hopefully that should be good enough for a repro.

**Comment by d-michail** [comment]
Some race condition maybe?

**Comment by d-michail** [comment]
Could you also try `DijkstraClosestFirstIterator`?  After making it public.

**Comment by shevek** [comment]
Not a race: I wrote a single-threaded junit test to render out 200 sample customer graphs, and we got a 2%-ish failure rate. It's consistent: the same cases always fail. The graph is always the same, only the starting node changes. I'll try to do an extract tomorrow or at the weekend; today's a bit deadline-filled, and there's a chance that bad language will be used unless I close some issues fairly fast.

**Comment by shevek** [comment]
This is not a complete self-contained test case, my apologies, but I dumped an anonymized graph from my application and captured the start nodes.
[pipeline-graph.dot.gz](https://github.com/jgrapht/jgrapht/files/1827616/pipeline-graph.dot.gz)

The call is:
```
Set<Node> srcNodes = [ n1316134250, n624662233 ] // these are the labels of the starting nodes.
GraphIterator<Node, DefaultEdge> srcIterator = new ClosestFirstIterator<>(srcGraph, srcNodes, 2);
... // iterate.
```

I'll try to make a more self-contained test case at some point - how does one best export and capture a graph to send to you? A graphviz export isn't really the best....

**Comment by jsichi** [comment]
I'm able to repro:

	at org.jgrapht.util.FibonacciHeap.decreaseKey(FibonacciHeap.java:129)
	at org.jgrapht.traverse.ClosestFirstIterator.encounterVertexAgain(ClosestFirstIterator.java:242)
	at org.jgrapht.traverse.CrossComponentIterator.addUnseenChildrenOf(CrossComponentIterator.java:307)
	at org.jgrapht.traverse.CrossComponentIterator.next(CrossComponentIterator.java:199)
	at Main.main(Main.java:79)

**Comment by jsichi** [comment]
I'm not even sure what the closest-first semantics are supposed to be for multiple start vertices.  Does it mean "closest with respect to any of these" (searching from all of them together at once, which seems useful) or "iterate everything starting from the first, then move on to the second, etc, skipping in cases of overlap" (the semantics used for DFS/BFS, which seems less useful).  @shevek which does your app expect?

**Comment by shevek** [comment]
Yes, we're looking to go outwards from a point, in a manner equivalent to iterating using BFS from a putative root. What happens is:

* Start from a root node.
* Manually iterate from the root node at a high level of detail.
* When you hit a threshold N, hand the current boundary-set to ClosestFirstIterator and keep iterating at low detail.

Looking at BFS now, that's less than useful for our purposes. I'll re-cast our algorithm again.

**Comment by d-michail** [comment]
@jsichi I would assume that it means "iterate everything starting from the first, then move on to the second if you have not reached everything, etc". Otherwise it gets more complicated and out-of-scope for a simple iterator.

**Comment by jsichi** [comment]
I isolated a small relevant subset of the repro graph and added it as a testcase (testMultipleStarts) in

https://github.com/jgrapht/jgrapht/pull/525/files

The problem was that ClosestFirstIterator called heap.clear() when it hit isConnectedComponentExhausted() due to the radius-bounded search, which led to the corrupted state, since we still had vertices which had been seen but not yet returned.  So when we encountered such a vertex again, we expected it to still be in the heap.

If we wanted to fix it to match the definition from @d-michail, I guess we could try to make it "unsee" the pending vertices at the time we call heap.clear.  But that seems complicated as well.  Also, the reason I say that definition seems less useful to me is that "closest first" should mean what it says, regardless of the order in which I supply the start vertices, otherwise the caller may see many "far" vertices before seeing a much closer one.  (One could argue the same for BFS, but let's not go there today.)

My fix follows what I called the more useful definition.  Conceptually, create a new vertex Vprime in the graph, attach a zero-length edge from Vprime to each of the start vertices, then run a single-source search starting from Vprime.  And consequently pretend it's a single component for the purposes of firing events.

(One could also argue, in my case with my past self, that ClosestFirstIterator should never have been a CrossComponentIterator, since the version that takes no start vertex also seems kind of weird.)

**Comment by shevek** [comment]
Yes, we're looking to go outwards from a point, in a manner equivalent to iterating using BFS from a putative root. What happens is:

* Start from a root node.
* Manually iterate from the root node at a high level of detail.
* When you hit a threshold N, hand the current boundary-set to ClosestFirstIterator and keep iterating at low detail.

Looking at BFS now, that's less than useful for our purposes. I'll re-cast our algorithm again.

I'm sorry the test was so huge, that was after significant reduction!

**Comment by jsichi** [comment]
I just merged the fix to master.  @shevek let me know when you get a chance to verify; it should show up in the latest SNAPSHOT.

**Comment by jsichi** [comment]
Cool, closing this one out.
