### ISSUE TITLE
UnsupportedOperationException while adding a weighted edge to the Pseudograph

### ISSUE THREAD

**Issue by Toptachamann** [jgrapht/jgrapht#592]
Hi,
Now I'm using Pseudograph class for testing my code and I run into the following problem:
The code below
``` java
Graph<Integer, DefaultWeightedEdge> graph = new Pseudograph<>(DefaultWeightedEdge.class);
Graphs.addEdgeWithVertices(graph, 1,2,5);
```
produces
```java
Exception in thread "main" java.lang.UnsupportedOperationException
	at org.jgrapht.graph.BaseIntrusiveEdgesSpecifics.setEdgeWeight(BaseIntrusiveEdgesSpecifics.java:136)
	at org.jgrapht.graph.AbstractBaseGraph.setEdgeWeight(AbstractBaseGraph.java:486)
	at org.jgrapht.Graphs.addEdge(Graphs.java:61)
	at org.jgrapht.Graphs.addEdgeWithVertices(Graphs.java:134)
	at org.jgrapht.alg.blossom.Main.main(Main.java:44)
```
I've rebased by branch on top of the master, but i hasn't solved the problem.

-------------------------------
On the other hand, the following code works fine
``` java
Graph<Integer, DefaultWeightedEdge> graph = new DefaultUndirectedWeightedGraph<>(DefaultWeightedEdge.class);
Graphs.addEdgeWithVertices(graph, 1,2,5);
```

------------------------------------
Is it a bug ot am I misunderstanding the way Pseudograph should be used?

**Comment by jsichi** [comment]
Use WeightedPseudograph instead

https://jgrapht.org/javadoc/org/jgrapht/graph/WeightedPseudograph.html

**Comment by Toptachamann** [comment]
Thanks!
