### ISSUE TITLE
ArrayIndexOutOfBoundsException in HeldKarpTSP

### ISSUE THREAD

**Issue by Toptachamann** [jgrapht/jgrapht#671]
I tested the Christofides algorithm with HeldKarpTSP and faced an ArrayIndexOutOfBoundsException:
``` console
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at org.jgrapht.alg.tour.HeldKarpTSP.getTour(HeldKarpTSP.java:193)
	at org.jgrapht.alg.matching.blossom.v5.MyGenerator.main(MyGenerator.java:32)
```

Here is a minimum working example: 
```
5
0 8 7 5 6 
8 0 3 1 7 
7 3 0 8 6 
5 1 8 0 1 
6 7 6 1 0 
```

**Comment by AlexandruValeanu** [comment]
I was unable to get an `ArrayIndexOutOfBoundsException` but I still found a bug using your test. Can you please test that if replacing https://github.com/jgrapht/jgrapht/blob/329eb432ba9d3646bac1fe4a7268d67e2f8417b7/jgrapht-core/src/main/java/org/jgrapht/alg/tour/HeldKarpTSP.java#L183 with https://github.com/jgrapht/jgrapht/blob/13c01711775b3c31bc84ba4bc722be3c4fee09bd/jgrapht-core/src/main/java/org/jgrapht/alg/tour/HeldKarpTSP.java#L181 solves the problem?

**Comment by AlexandruValeanu** [comment]
Can you please check again?
