### ISSUE TITLE
Android App crashing on start "RuntimeException: Unable to instantiate activity ..."

### ISSUE THREAD

**Issue by AntonioDell** [jgrapht/jgrapht#692]
When trying to use JGraphT in my android project, the dependency is loaded from maven, I can use all classes, but when starting the app in the emulator or  test device, it instantly crashes.

Here the full Stacktrace:
```2018-10-10 17:32:24.264 31107-31107/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.prototype.antonio.myapplication, PID: 31107
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{de.prototype.antonio.myapplication/de.prototype.antonio.myapplication.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "de.prototype.antonio.myapplication.MainActivity" on path: DexPathList[[zip file "/data/app/de.prototype.antonio.myapplication-ITg2wdZRXslry-84TvN0ag==/base.apk"],nativeLibraryDirectories=[/data/app/de.prototype.antonio.myapplication-ITg2wdZRXslry-84TvN0ag==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3092)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "de.prototype.antonio.myapplication.MainActivity" on path: DexPathList[[zip file "/data/app/de.prototype.antonio.myapplication-ITg2wdZRXslry-84TvN0ag==/base.apk"],nativeLibraryDirectories=[/data/app/de.prototype.antonio.myapplication-ITg2wdZRXslry-84TvN0ag==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1178)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3082)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/AppCompatActivity;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 12 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/de.prototype.antonio.myapplication-ITg2wdZRXslry-84TvN0ag==/base.apk"],nativeLibraryDirectories=[/data/app/de.prototype.antonio.myapplication-ITg2wdZRXslry-84TvN0ag==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 15 more
```

Here you have a minimal example for this issue:
https://github.com/AntonioDell/JgraphTAndroidIssue

**EDIT**
Additional Information:
- I first thought it was  multidex issue, but it turns out that my original project is way below the limit (using an gradle plugin which generated the following output):
```
:app:countDebugDexMethods
Total methods in app-debug.apk: 29889 (45,61% used)
Total fields in app-debug.apk:  17993 (27,46% used)
Total classes in app-debug.apk:  3430 (5,23% used)
Methods remaining in app-debug.apk: 35646
Fields remaining in app-debug.apk:  47542
Classes remaining in app-debug.apk:  62105
```
- The stacktrace doesn't say that it's an issue with JGraphT explicitly, but a test branch in the minimum example (https://github.com/AntonioDell/JgraphTAndroidIssue/tree/works-without-jgrapht) shows, that the issue is introduced by the dependency

**Comment by Toptachamann** [comment]
Hi,

Could you include also the part of the stacktrace that contains the error caused by JGraphT dependency? It is now unclear why the problem is caused by JGraphT dependency. Now we can see only `Didn't find class "android.support.v7.app.AppCompatActivity"`.

**Comment by AntonioDell** [comment]
Hello,

thanks for your reply.

The issue is introduced by importing the dependency from maven. please check the second branch (https://github.com/AntonioDell/JgraphTAndroidIssue/tree/works-without-jgrapht) which should execute just fine.
The only difference is, that the dependency isn't added.

**Comment by jsichi** [comment]
The crash report looks similar to this one:

https://stackoverflow.com/questions/43893613/classnotfoundexception-appcompatactivity-class-after-moving-android-studio-pro/43893757

So while there could be a JGraphT issue (we've had Android compatibility issues in the past), it might be circumstantial.
