### ISSUE TITLE
Android: issue with API level 21 (API 24+ ok)

### ISSUE THREAD

**Issue by nickw1** [jgrapht/jgrapht#762]
Hi,

Have read the previous issues (e.g #312) for Android, but it's my understanding that Android Studio works fine with Java 8 and in particular lambdas (see https://developer.android.com/studio/write/java8-support).

However I'm getting a lambda-related crash with JGraphT 1.3.0 on an Android 5.0 device (a 7.1 device works fine). Stack trace:

 java.lang.NoClassDefFoundError: org.jgrapht.util.-$$Lambda$SupplierUtil$WPFsTubLsTPZK1hUPRdhSf51FVU
        at org.jgrapht.util.SupplierUtil.createSupplier(SupplierUtil.java:60)
        at org.jgrapht.util.SupplierUtil.<clinit>(SupplierUtil.java:38)
        at org.jgrapht.graph.DefaultUndirectedWeightedGraph.<init>(DefaultUndirectedWeightedGraph.java:48)
        at freemap.hikar.signposting.GraphManager.<init>(GraphManager.kt:77)
        at freemap.hikar.signposting.SignpostManager.<init>(SignpostManager.kt:22)
        at freemap.hikar.MainActivity.onCreate(MainActivity.kt:107)
        at android.app.Activity.performCreate(Activity.java:5933)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
        at android.app.ActivityThread.access$800(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

The code causing the crash is returning a lambda.

The error arises from this call in my code to create the graph:

 var graph = DefaultUndirectedWeightedGraph<Point, IdWeightedEdge>(IdWeightedEdge::class.java)

My app has a minSdk of 14, targetSdk of 27 and is using Kotlin - and I have added Java 1.8 support to my app's build.gradle.

Thanks,
Nick

**Comment by d-michail** [comment]
Could you try using the other constructor 
```
DefaultUndirectedWeightedGraph(Supplier<V> vertexSupplier, Supplier<E> edgeSupplier)
```
where you supply the suppliers explicitly? If you do not call method `addVertex()` you can use `null` for the vertex supplier and `IdWeightedEdge::new` for the edge supplier.

You could also try to instantiate a graph with `DefaultWeightedEdge` to check if everything works fine.

**Comment by nickw1** [comment]
When using the other constructor with null for both suppliers (I never need a supplier, I always use addVertex() and addEdge()) I get a similar but different error:

` java.lang.NoClassDefFoundError: org.jgrapht.graph.-$$Lambda$AbstractBaseGraph$BackwardsCompatibleGraphSpecificsStrategy$qw26bacSKCo7unrfgFBh629cRI0
        at org.jgrapht.graph.AbstractBaseGraph$BackwardsCompatibleGraphSpecificsStrategy.getSpecificsFactory(AbstractBaseGraph.java:617)
        at org.jgrapht.graph.AbstractBaseGraph.<init>(AbstractBaseGraph.java:106)
        at org.jgrapht.graph.DefaultUndirectedGraph.<init>(DefaultUndirectedGraph.java:59)
        at org.jgrapht.graph.DefaultUndirectedWeightedGraph.<init>(DefaultUndirectedWeightedGraph.java:59)
        at freemap.hikar.signposting.GraphManager.<init>(GraphManager.kt:21)
        at freemap.hikar.signposting.SignpostManager.<init>(SignpostManager.kt:22)
        at freemap.hikar.MainActivity.onCreate(MainActivity.kt:105)
        at android.app.Activity.performCreate(Activity.java:5933)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
        at android.app.ActivityThread.access$800(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)`

I'll try and test DefaultWeightedEdge (un-subclassed) if I have a moment.

**Comment by d-michail** [comment]
Last time someone had similar issues, the solution was to try and replace some lambdas and other Java 8 features with older constructs.  

Maybe it is best to compile JGraphT from the master branch and try to replace the malfunctioning constructs. The one in your latest example has been removed from the master branch.

My understanding is that until some point the Java 8 support in Android was really buggy.

**Comment by geometer** [comment]
java.util.function.Supplilier interface is only available in API 24+. https://developer.android.com/studio/write/java8-support
