### ISSUE TITLE
IllegalArgumentException when adding edges: no such edge in graph

### ISSUE THREAD

**Issue by spi-x-i** [jgrapht/jgrapht#771]
```
 * JGraphT version: 1.3.0
 * Java version (java -version)/platform: 1.8, Scala version: 2.11.12
```
**Issue**
Whenever I attempt to add an edge to my `DirectedAcyclicGraph[String, Pizza]`  with a custom object `E`, I'm recording the following exception:
```
java.lang.IllegalArgumentException: no such edge in graph: Pizza(<attributes-of-my-pizza-objects>)
	at org.jgrapht.graph.BaseIntrusiveEdgesSpecifics.getEdgeSource(BaseIntrusiveEdgesSpecifics.java:99)
	at org.jgrapht.graph.AbstractBaseGraph.getEdgeSource(AbstractBaseGraph.java:321)
	at org.jgrapht.graph.specifics.FastLookupDirectedSpecifics.addEdgeToTouchingVertices(FastLookupDirectedSpecifics.java:150)
	at org.jgrapht.graph.AbstractBaseGraph.addEdge(AbstractBaseGraph.java:276)
	at org.jgrapht.graph.DirectedAcyclicGraph.addEdge(DirectedAcyclicGraph.java:284)
	at io.radicalbit.rtsae.models.PipelineGraphImpl.addConnection(PipelineGraphImpl.scala:90)
```

**Steps to reproduce**
```
addEdge("sourceString", "sinkString", pizzaObject)
```

**Expected behavior**

I'd expect my edge plain inserted. I cannot explain why I receive a not found error on an edge I still have to insert. I've also observed that `BaseIntrusiveEdgesSpecifics.getEdgeSource(E e)` search the source vertex by the edge, but how can the edge exist in the graph if it has not yet been inserted? I'm scared this can be due to my trivial error.

Thank you guys for your kindness and your great work!

Andrea

**Comment by spi-x-i** [comment]
I found the solution to my problem.
I was actually calling `addEdge` on a _cloned_ graph.
```
val clonedGraph = existingGraph.clone()
clonedGraph.addEdge(...)
```
It worked like a charm on the original instance. 
I think that is related to the _two step_ edge insertion: the second step'd search for the edge in the first one, but the second one resides to the _cloned_ object, not into the copy as the first.

**Comment by spi-x-i** [comment]
I found the solution to my problem.
I was actually calling `addEdge` on a _cloned_ graph.
```
val clonedGraph = existingGraph.clone()
clonedGraph.addEdge(...)
```
It worked like a charm on the original instance. 
I think that is related to the _two step_ edge insertion: the second step'd search for the edge in the first one, but the second one resides to the _cloned_ object, not into the copy as the first.
