### ISSUE TITLE
Add edge between vertices with custom equals/hash methods

### ISSUE THREAD

**Issue by sergmain** [jgrapht/jgrapht#904]
```
 * JGraphT version: 1.4.0
 * Java version (java -version)/platform:  
windows openjdk 11.0.4, 
windows OpenJDK11U-jdk_x64_windows_hotspot_11.0.6_10
```

**Issue**
Add edge between vertices with custom equals/hash methods

```
error message is:
java.lang.IllegalArgumentException: no such vertex in graph: TestJGrapht.Item(id=1, itemId=1001, code=code-1001)

	at org.jgrapht.graph.AbstractGraph.assertVertexExist(AbstractGraph.java:131)
	at org.jgrapht.graph.DirectedAcyclicGraph.addEdge(DirectedAcyclicGraph.java:278)
```

**Steps to reproduce (small coding example)**

there is unit-test for reproducing:

```
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import org.jgrapht.graph.DefaultEdge;
import org.jgrapht.graph.DirectedAcyclicGraph;
import org.jgrapht.util.SupplierUtil;
import org.junit.jupiter.api.Test;

import java.util.concurrent.atomic.AtomicLong;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * @author Serge
 * Date: 4/10/2020
 * Time: 5:12 PM
 */
public class TestJGrapht {

    @Data
    @EqualsAndHashCode(of = "itemId")
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Item {
        public Long id;
        public Long itemId;
        public String code;

        public Item(long id) {
            this.id = id;
        }
    }

    @Test
    public void test() {
        DirectedAcyclicGraph<Item, DefaultEdge> graph = new DirectedAcyclicGraph<>(
                Item::new, SupplierUtil.DEFAULT_EDGE_SUPPLIER, false, true);

        AtomicLong id = new AtomicLong();
        graph.setVertexSupplier(()->new Item(id.incrementAndGet()));

        final Item v1001 = graph.addVertex();
        assertNotNull(v1001.id);
        v1001.itemId = 1001L;
        v1001.code = "code-1001";

        Item item = graph.vertexSet()
                .stream()
                .filter(o -> o.itemId.equals(1001L))
                .findAny().orElse(null);
        assertNotNull(item);
        assertEquals(v1001.id, item.id);

        final Item v1002 = graph.addVertex();
        assertNotNull(v1002.id);
        v1002.itemId = 1002L;
        v1002.code = "code-1002";

        item = graph.vertexSet()
                .stream()
                .filter(o -> o.itemId.equals(1002L))
                .findAny().orElse(null);
        assertNotNull(item);
        assertEquals(v1002.id, item.id);

        graph.addEdge(v1001, v1002);
    }

}
```
or use this test
https://github.com/sergmain/metaheuristic/blob/master/apps/metaheuristic/src/test/java/ai/metaheuristic/ai/graph/TestJGrapht.java

**Expected behaviour**

unit-test must be completed without an error

**Other information**

**Comment by sergmain** [comment]
I've tried different types of Item.itemId and found that the test is ok with type String and long.

**Comment by d-michail** [comment]
Please do not open issues without first reading through the user guide and before searching the already closed issues.

The user guide is located here: https://jgrapht.org/guide/UserOverview . 
It also contains a link to a document explaining exactly the requirements for your vertex and/or edges: https://jgrapht.org/guide/VertexAndEdgeTypes . 

The mailing list is the correct channel if you are looking for help on how to use the library.
